import { DEFAULT_REFERENCE_CANVAS, type CaseTemplate } from "@/lib/design/types";

import { DESIGNED_TEMPLATES } from "./designed.templates.generated";

const REF = DEFAULT_REFERENCE_CANVAS;

export const CASE_TEMPLATES: CaseTemplate[] = [
  ...DESIGNED_TEMPLATES,
  {
    id: "tpl-minimal-text",
    slug: "minimal-text",
    title: "متن مینیمال",
    description: "نام یا عبارت دلخواه با استیکر ساده — مناسب هر مدل گوشی",
    thumbnail: "/cases/stickers/circle.svg",
    tags: ["مینیمال", "متن"],
    referenceCanvas: REF,
    layers: [
      {
        id: "tpl-layer-1",
        type: "text",
        text: "YOUR NAME",
        fontFamily: "CaseEditorVazirmatn",
        fontSize: 36,
        fill: "#ffffff",
        align: "center",
        width: 238,
        name: "نام",
        visible: true,
        x: 140,
        y: 280,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
      {
        id: "tpl-layer-2",
        type: "image",
        src: "/cases/stickers/circle.svg",
        width: 80,
        height: 80,
        isSticker: true,
        name: "دایره",
        visible: true,
        x: 100,
        y: 400,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
    ],
  },
  {
    id: "tpl-neon-gaming",
    slug: "neon-gaming",
    title: "گیمینگ نئون",
    description: "استیکرهای رعد و آتش با تایپوگرافی پیکسلی برای گیمرها",
    thumbnail: "/cases/stickers/bolt.svg",
    tags: ["گیمینگ", "نئون"],
    referenceCanvas: REF,
    layers: [
      {
        id: "tpl-layer-3",
        type: "text",
        text: "GAME ON",
        fontFamily: "CaseEditorPixel",
        fontSize: 32,
        fill: "#06b6d4",
        align: "center",
        width: 238,
        name: "عنوان",
        visible: true,
        x: 140,
        y: 200,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
      {
        id: "tpl-layer-4",
        type: "image",
        src: "/cases/stickers/bolt.svg",
        width: 64,
        height: 64,
        isSticker: true,
        name: "رعد",
        visible: true,
        x: 108,
        y: 320,
        rotation: -15,
        scaleX: 1.2,
        scaleY: 1.2,
      },
      {
        id: "tpl-layer-5",
        type: "image",
        src: "/cases/stickers/fire.svg",
        width: 64,
        height: 64,
        isSticker: true,
        name: "آتش",
        visible: true,
        x: 160,
        y: 380,
        rotation: 10,
        scaleX: 1,
        scaleY: 1,
      },
    ],
  },
  {
    id: "tpl-floral",
    slug: "floral-bloom",
    title: "شکوفه گل",
    description: "گل و برگ با متن زیبا — مناسب استایل زنانه و بهاری",
    thumbnail: "/cases/stickers/flower.svg",
    tags: ["گل", "زنانه"],
    referenceCanvas: REF,
    layers: [
      {
        id: "tpl-layer-6",
        type: "image",
        src: "/cases/stickers/flower.svg",
        width: 96,
        height: 96,
        isSticker: true,
        name: "گل",
        visible: true,
        x: 92,
        y: 220,
        rotation: 0,
        scaleX: 1.5,
        scaleY: 1.5,
      },
      {
        id: "tpl-layer-7",
        type: "image",
        src: "/cases/stickers/leaf.svg",
        width: 72,
        height: 72,
        isSticker: true,
        name: "برگ",
        visible: true,
        x: 50,
        y: 350,
        rotation: -30,
        scaleX: 1,
        scaleY: 1,
      },
      {
        id: "tpl-layer-8",
        type: "text",
        text: "زیبایی",
        fontFamily: "CaseEditorCristik",
        fontSize: 40,
        fill: "#f472b6",
        align: "center",
        width: 238,
        name: "متن",
        visible: true,
        x: 140,
        y: 420,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
    ],
  },
  {
    id: "tpl-cyber-grid",
    slug: "cyber-grid",
    title: "شبکه سایبری",
    description: "استایل سایبرپانک با المان‌های نئونی و گیم‌پد",
    thumbnail: "/cases/stickers/gamepad.svg",
    tags: ["گیمینگ", "سایبر"],
    referenceCanvas: REF,
    layers: [
      {
        id: "tpl-layer-9",
        type: "text",
        text: "CYBER",
        fontFamily: "CaseEditorPixel",
        fontSize: 36,
        fill: "#22d3ee",
        align: "center",
        width: 238,
        name: "عنوان",
        visible: true,
        x: 140,
        y: 180,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
      {
        id: "tpl-layer-10",
        type: "image",
        src: "/cases/stickers/gamepad.svg",
        width: 80,
        height: 80,
        isSticker: true,
        name: "گیم‌پد",
        visible: true,
        x: 100,
        y: 300,
        rotation: 0,
        scaleX: 1.3,
        scaleY: 1.3,
      },
      {
        id: "tpl-layer-11",
        type: "image",
        src: "/cases/stickers/zigzag.svg",
        width: 120,
        height: 40,
        isSticker: true,
        name: "زیگ‌زاگ",
        visible: true,
        x: 80,
        y: 420,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
    ],
  },
  {
    id: "tpl-marble-gold",
    slug: "marble-gold",
    title: "مرمر طلایی",
    description: "استیکر الماس با متن لوکس — حس مرمر و طلا",
    thumbnail: "/cases/stickers/diamond.svg",
    tags: ["لوکس", "مینیمال"],
    referenceCanvas: REF,
    layers: [
      {
        id: "tpl-layer-12",
        type: "image",
        src: "/cases/stickers/diamond.svg",
        width: 72,
        height: 72,
        isSticker: true,
        name: "الماس",
        visible: true,
        x: 104,
        y: 240,
        rotation: 0,
        scaleX: 1.8,
        scaleY: 1.8,
      },
      {
        id: "tpl-layer-13",
        type: "text",
        text: "LUXURY",
        fontFamily: "CaseEditorSorena",
        fontSize: 34,
        fill: "#d4af37",
        align: "center",
        width: 238,
        name: "متن",
        visible: true,
        x: 140,
        y: 380,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
    ],
  },
  {
    id: "tpl-racing-stripes",
    slug: "racing-stripes",
    title: "خطوط مسابقه",
    description: "طراحی اسپرت با خطوط زیگ‌زاگ و تاج قهرمانی",
    thumbnail: "/cases/stickers/crown.svg",
    tags: ["اسپرت", "مردانه"],
    referenceCanvas: REF,
    layers: [
      {
        id: "tpl-layer-14",
        type: "image",
        src: "/cases/stickers/zigzag.svg",
        width: 200,
        height: 60,
        isSticker: true,
        name: "خطوط",
        visible: true,
        x: 40,
        y: 260,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
      {
        id: "tpl-layer-15",
        type: "image",
        src: "/cases/stickers/crown.svg",
        width: 64,
        height: 64,
        isSticker: true,
        name: "تاج",
        visible: true,
        x: 108,
        y: 360,
        rotation: 0,
        scaleX: 1.4,
        scaleY: 1.4,
      },
      {
        id: "tpl-layer-16",
        type: "text",
        text: "RACE",
        fontFamily: "CaseEditorPixel",
        fontSize: 28,
        fill: "#ef4444",
        align: "center",
        width: 238,
        name: "عنوان",
        visible: true,
        x: 140,
        y: 460,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
    ],
  },
  {
    id: "tpl-cosmic",
    slug: "cosmic",
    title: "کهکشانی",
    description: "ماه، ستاره و متن رویایی برای دوستداران فضا",
    thumbnail: "/cases/stickers/moon.svg",
    tags: ["فضایی", "محبوب"],
    referenceCanvas: REF,
    layers: [
      {
        id: "tpl-layer-17",
        type: "image",
        src: "/cases/stickers/moon.svg",
        width: 80,
        height: 80,
        isSticker: true,
        name: "ماه",
        visible: true,
        x: 100,
        y: 200,
        rotation: 0,
        scaleX: 1.5,
        scaleY: 1.5,
      },
      {
        id: "tpl-layer-18",
        type: "image",
        src: "/cases/stickers/star.svg",
        width: 48,
        height: 48,
        isSticker: true,
        name: "ستاره",
        visible: true,
        x: 180,
        y: 280,
        rotation: 15,
        scaleX: 1.2,
        scaleY: 1.2,
      },
      {
        id: "tpl-layer-19",
        type: "text",
        text: "DREAM",
        fontFamily: "CaseEditorCristik",
        fontSize: 38,
        fill: "#a78bfa",
        align: "center",
        width: 238,
        name: "متن",
        visible: true,
        x: 140,
        y: 400,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
    ],
  },
  {
    id: "tpl-sunny-vibes",
    slug: "sunny-vibes",
    title: "انرژی خورشید",
    description: "خورشید و موج با حس شاد و تابستانی",
    thumbnail: "/cases/stickers/sun.svg",
    tags: ["تابستان", "شاد"],
    referenceCanvas: REF,
    layers: [
      {
        id: "tpl-layer-20",
        type: "image",
        src: "/cases/stickers/sun.svg",
        width: 88,
        height: 88,
        isSticker: true,
        name: "خورشید",
        visible: true,
        x: 96,
        y: 220,
        rotation: 0,
        scaleX: 1.4,
        scaleY: 1.4,
      },
      {
        id: "tpl-layer-21",
        type: "image",
        src: "/cases/stickers/wave.svg",
        width: 160,
        height: 48,
        isSticker: true,
        name: "موج",
        visible: true,
        x: 60,
        y: 380,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
      {
        id: "tpl-layer-22",
        type: "text",
        text: "SUMMER",
        fontFamily: "CaseEditorVazirmatn",
        fontSize: 30,
        fill: "#fbbf24",
        align: "center",
        width: 238,
        name: "متن",
        visible: true,
        x: 140,
        y: 460,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
      },
    ],
  },
];

export function getCaseTemplateBySlug(slug: string): CaseTemplate | undefined {
  return CASE_TEMPLATES.find((t) => t.slug === slug);
}

export function getUniversalTemplates(): CaseTemplate[] {
  return CASE_TEMPLATES;
}

export function getDesignedTemplates(): CaseTemplate[] {
  return DESIGNED_TEMPLATES;
}

export function getFeaturedTemplates(limit = 4): CaseTemplate[] {
  return CASE_TEMPLATES.slice(0, limit);
}

export function getTemplatesForModel(
  _brandSlug: string,
  _modelSlug: string,
  _caseTypeSlug: string,
): CaseTemplate[] {
  return CASE_TEMPLATES;
}

export function getAllTemplates(): CaseTemplate[] {
  return CASE_TEMPLATES;
}
