import type { ShopProduct } from "./types";

const SHOP_PLACEHOLDER_IMAGE = "/cases/og-default.jpg";

export const STATIC_SHOP_PRODUCTS: ShopProduct[] = [
  // PS5 consoles
  {
    id: "ps5-disc-1tb-new",
    slug: "ps5-disc-1tb-new",
    title: "PS5 دیسک 1TB",
    console: "ps5",
    category: "console",
    condition: "new",
    price: 33800000,
    compareAtPrice: 35200000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "1TB",
    edition: "Disc",
    inStock: true,
    badges: ["نو", "ضمانت تست"],
    highlights: ["کابل کامل", "ریجن آزاد"],
    searchTerms: ["playstation 5 disc", "ps5 disc", "پلی استیشن 5 دیسک"],
  },
  {
    id: "ps5-digital-used",
    slug: "ps5-digital-used",
    title: "PS5 دیجیتال",
    console: "ps5",
    category: "console",
    condition: "used",
    price: 27800000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "825GB",
    edition: "Digital",
    inStock: true,
    badges: ["دست دوم", "تست شده"],
    highlights: ["کم کارکرد", "بدون ریپیر"],
  },
  {
    id: "ps5-slim-disc-new",
    slug: "ps5-slim-disc-new",
    title: "PS5 Slim دیسک",
    console: "ps5",
    category: "console",
    condition: "new",
    price: 36400000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "1TB",
    edition: "Slim",
    inStock: false,
    badges: ["نو"],
    highlights: ["نسخه جدید", "مصرف کمتر"],
    searchTerms: ["slim", "اسلیم", "playstation 5 slim", "ps5 slim"],
  },
  // PS4 consoles
  {
    id: "ps4-slim-1tb-used",
    slug: "ps4-slim-1tb-used",
    title: "PS4 Slim 1TB",
    console: "ps4",
    category: "console",
    condition: "used",
    price: 12200000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "1TB",
    inStock: true,
    badges: ["دست دوم", "تست شده"],
    highlights: ["فن سرویس شده", "ظاهر تمیز"],
  },
  {
    id: "ps4-pro-1tb-used",
    slug: "ps4-pro-1tb-used",
    title: "PS4 Pro 1TB",
    console: "ps4",
    category: "console",
    condition: "used",
    price: 14500000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "1TB",
    inStock: true,
    badges: ["دست دوم", "تست شده"],
    highlights: ["پشتیبانی 4K", "گارانتی تست"],
  },
  {
    id: "ps4-slim-500-new",
    slug: "ps4-slim-500-new",
    title: "PS4 Slim 500GB",
    console: "ps4",
    category: "console",
    condition: "new",
    price: 16800000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "500GB",
    inStock: false,
    badges: ["نو"],
    highlights: ["پلمپ", "تعداد محدود"],
  },
  // Xbox Series consoles
  {
    id: "xbox-series-x-new",
    slug: "xbox-series-x-new",
    title: "Xbox Series X",
    console: "xbox-series",
    category: "console",
    condition: "new",
    price: 34600000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "1TB",
    inStock: true,
    badges: ["نو", "ضمانت تست"],
    highlights: ["قدرت بالا", "مناسب 4K"],
    searchTerms: ["series x", "xbox series x", "xsx"],
  },
  {
    id: "xbox-series-s-used",
    slug: "xbox-series-s-used",
    title: "Xbox Series S",
    console: "xbox-series",
    category: "console",
    condition: "used",
    price: 18300000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "512GB",
    inStock: true,
    badges: ["دست دوم", "تست شده"],
    highlights: ["بدون ایراد", "تحویل فوری"],
    searchTerms: ["series s", "xbox series s", "xss"],
  },
  {
    id: "xbox-one-s-used",
    slug: "xbox-one-s-used",
    title: "Xbox One S",
    console: "xbox-one",
    category: "console",
    condition: "used",
    price: 9600000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "1TB",
    inStock: true,
    badges: ["دست دوم", "اقتصادی"],
    highlights: ["تست کامل", "قیمت مناسب"],
  },
  {
    id: "xbox-one-x-used",
    slug: "xbox-one-x-used",
    title: "Xbox One X",
    console: "xbox-one",
    category: "console",
    condition: "used",
    price: 11600000,
    image: SHOP_PLACEHOLDER_IMAGE,
    storage: "1TB",
    inStock: true,
    badges: ["دست دوم", "تست شده"],
    highlights: ["توان پردازشی بالاتر", "گارانتی تست"],
  },

  // PS5 tools
  {
    id: "ps5-dualsense-new",
    slug: "ps5-dualsense-new",
    title: "دسته DualSense PS5",
    console: "ps5",
    category: "tools",
    condition: "new",
    price: 4200000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["اورجینال"],
    highlights: ["هپتیک فیدبک", "تریگر تطبیقی"],
    searchTerms: ["dualsense", "dual sense", "دوالسنس", "دسته ps5", "controller ps5"],
  },
  {
    id: "ps5-charging-dock",
    slug: "ps5-charging-dock",
    title: "پایه شارژ دو دسته PS5",
    console: "ps5",
    category: "tools",
    condition: "new",
    price: 1850000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["شارژ سریع"],
    highlights: ["دو پورت شارژ", "LED وضعیت"],
  },
  // PS4 tools
  {
    id: "ps4-dualshock-new",
    slug: "ps4-dualshock-new",
    title: "دسته DualShock 4",
    console: "ps4",
    category: "tools",
    condition: "new",
    price: 2650000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["سازگار PS4"],
    highlights: ["تاچ پد", "اسپیکر داخلی"],
    searchTerms: ["dualshock", "dual shock 4", "دسته ps4"],
  },
  {
    id: "ps4-cooling-stand",
    slug: "ps4-cooling-stand",
    title: "پایه خنک‌کننده PS4",
    console: "ps4",
    category: "tools",
    condition: "new",
    price: 980000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["خنک‌کننده"],
    highlights: ["کاهش دما", "فن بی‌صدا"],
  },
  // Xbox Series tools
  {
    id: "xbox-series-controller",
    slug: "xbox-series-controller",
    title: "دسته Xbox Series",
    console: "xbox-series",
    category: "tools",
    condition: "new",
    price: 3950000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["سازگار Series"],
    highlights: ["بلوتوث", "باتری قابل تعویض"],
  },
  {
    id: "xbox-series-charging-station",
    slug: "xbox-series-charging-station",
    title: "ایستگاه شارژ Xbox Series",
    console: "xbox-series",
    category: "tools",
    condition: "new",
    price: 2100000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["دو دسته"],
    highlights: ["شارژ همزمان", "طراحی فشرده"],
  },
  // Xbox One tools
  {
    id: "xbox-one-controller",
    slug: "xbox-one-controller",
    title: "دسته Xbox One",
    console: "xbox-one",
    category: "tools",
    condition: "new",
    price: 2350000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["سازگار One"],
    highlights: ["ارگونومیک", "دوام بالا"],
  },
  {
    id: "xbox-one-cooling-stand",
    slug: "xbox-one-cooling-stand",
    title: "پایه خنک‌کننده Xbox One",
    console: "xbox-one",
    category: "tools",
    condition: "new",
    price: 890000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["خنک‌کننده"],
    highlights: ["کاهش صدا", "نصب آسان"],
  },

  // PS5 accessories
  {
    id: "ps5-hdmi-21",
    slug: "ps5-hdmi-21",
    title: "کابل HDMI 2.1 برای PS5",
    console: "ps5",
    category: "accessories",
    condition: "new",
    price: 650000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["4K 120Hz"],
    highlights: ["طول ۲ متر", "کیفیت بالا"],
    searchTerms: ["hdmi", "hdmi 2.1", "کابل hdmi", "کابل"],
  },
  {
    id: "ps5-headset",
    slug: "ps5-headset",
    title: "هدست گیمینگ PS5",
    console: "ps5",
    category: "accessories",
    condition: "new",
    price: 3200000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["صدای فراگیر"],
    highlights: ["میکروفون نویزگیر", "راحت برای بازی طولانی"],
    searchTerms: ["headset", "هدست", "هدفون گیمینگ"],
  },
  {
    id: "ps4-hdmi-cable",
    slug: "ps4-hdmi-cable",
    title: "کابل HDMI PS4",
    console: "ps4",
    category: "accessories",
    condition: "new",
    price: 380000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["اورجینال"],
    highlights: ["طول ۱.۵ متر", "سازگار PS4"],
  },
  {
    id: "ps4-carry-case",
    slug: "ps4-carry-case",
    title: "کیف حمل PS4",
    console: "ps4",
    category: "accessories",
    condition: "new",
    price: 1250000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["ضد ضربه"],
    highlights: ["جای دسته", "محافظت کامل"],
  },
  // Xbox Series accessories
  {
    id: "xbox-series-hdmi-21",
    slug: "xbox-series-hdmi-21",
    title: "کابل HDMI 2.1 Xbox Series",
    console: "xbox-series",
    category: "accessories",
    condition: "new",
    price: 680000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["4K 120Hz"],
    highlights: ["VRR", "طول ۲ متر"],
  },
  {
    id: "xbox-series-headset",
    slug: "xbox-series-headset",
    title: "هدست گیمینگ Xbox Series",
    console: "xbox-series",
    category: "accessories",
    condition: "new",
    price: 2950000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["صدای فراگیر"],
    highlights: ["سازگار Xbox", "میکروفون قابل جدا شدن"],
  },
  // Xbox One accessories
  {
    id: "xbox-one-hdmi-cable",
    slug: "xbox-one-hdmi-cable",
    title: "کابل HDMI Xbox One",
    console: "xbox-one",
    category: "accessories",
    condition: "new",
    price: 350000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["اورجینال"],
    highlights: ["طول ۱.۵ متر", "کیفیت پایدار"],
  },
  {
    id: "xbox-one-thumb-grips",
    slug: "xbox-one-thumb-grips",
    title: "روکش آنالوگ Xbox One",
    console: "xbox-one",
    category: "accessories",
    condition: "new",
    price: 280000,
    image: SHOP_PLACEHOLDER_IMAGE,
    inStock: true,
    badges: ["ضد لغزش"],
    highlights: ["ست ۴ عددی", "نصب آسان"],
  },
];
